theme: jekyll-theme-slate
title: Jonah Gannon - Astrophysicist 
description: Currently working on my PhD thesis under Prof. Duncan Forbes at Swinburne University, Melbourne, Australia
layout: sidebar
